INSERT INTO BuildConfig(id,buildname,tabtp,shownotice,layer,resource,red,effect,userlevel,fuben,previd,touchType,touchParam,"offset",lockset,camerapos,cameratime,remind,describe,close) VALUES(20,'保衛聖域',2,'1','','jianzhu20','shouhushengyu','eff_scene_shsy_rukou',1,101004,101003,1,'holyland/HolyLand','0|-50','','',0,1,'在保衛聖域中，將會面臨強大的冥王軍的挑戰，只有強者才能戰鬥至最後',1);
UPDATE ConstantsConfig SET val='1.0.193' WHERE id=6000;
UPDATE ConstantsConfig SET val='1540' WHERE id=6004;
UPDATE DropbaseConfig SET weight=100 WHERE rowid=9113;
UPDATE DropbaseConfig SET weight=100 WHERE rowid=9114;
UPDATE DropbaseConfig SET weight=100 WHERE rowid=9209;
UPDATE DropbaseConfig SET weight=100 WHERE rowid=9210;
UPDATE DropbaseConfig SET weight=100 WHERE rowid=9296;
UPDATE DropbaseConfig SET weight=100 WHERE rowid=9297;
UPDATE DropbaseConfig SET weight=100 WHERE rowid=9360;
UPDATE DropbaseConfig SET weight=100 WHERE rowid=9361;
INSERT INTO EndlessPowerConfig(id,name,pic,quality,level,condition,param,prop1,value1,gwnum1,prop2,value2,gwnum2,prop3,value3,gwnum3,prop4,value4,gwnum4,skillid,remove,remakeid,remakenum) VALUES(750036,'Rose de la mort','sds_alaiyeshi_68',5,6,3,'65307|14302',8,0.015,0.0015,9,0.01,0.001,34,0.08,0.0,0,0.0,0.0,41451,0,700002,120);
INSERT INTO EndlessPowerConfig(id,name,pic,quality,level,condition,param,prop1,value1,gwnum1,prop2,value2,gwnum2,prop3,value3,gwnum3,prop4,value4,gwnum4,skillid,remove,remakeid,remakenum) VALUES(750037,'Clémence','sds_alaiyeshi_69',5,6,3,'43303|45302|55303',9,0.01,0.001,35,3.0,0.3,25,80.0,0.0,0,0.0,0.0,41457,0,700002,120);
UPDATE GoodsConfig SET id=16010033, goodsid=16010 WHERE rowid=1860;
UPDATE GoodsConfig SET id=16010034, goodsid=16010 WHERE rowid=1861;
UPDATE GoodsConfig SET id=16014031, goodsid=16014 WHERE rowid=1915;
UPDATE GoodsConfig SET id=16014032, goodsid=16014 WHERE rowid=1916;
UPDATE GoodsConfig SET id=16014033, goodsid=16014 WHERE rowid=1917;
UPDATE GoodsConfig SET id=16014034, goodsid=16014 WHERE rowid=1918;
UPDATE HeroConfig SET name='Suikyo' WHERE id=65207;
UPDATE HeroStoryConfig SET describe='Chevalier de bronze de Pégase lors de la dernière Guerre Sainte. Ami d''enfance de Sasha. Bien qu''il ait été un bandit lorsqu''il était enfant, il a ressenti la chaleur de sa rencontre avec Suikyo Chevalier d''argent de Coupe alors qu''il se réfugiait dans les montagnes enneigées. Depuis, il s''est amendé et est devenu le disciple de Suikyo et l''ami d''Alone.' WHERE id=33203;
UPDATE HeroStoryConfig SET describe='Chevalier d''or respecté par Shion et Dohko, est très fort. Il est très loyal envers Athéna et possède une puissance écrasante. Il a vaincu plusieurs Spectres qui ont envahi la Maison du Taureau, puis a perdu contre Suikyo de Garuda, ce qui lui a permis de traverser la Maison du Taureau.' WHERE id=44103;
UPDATE HeroStoryConfig SET describe='Avec ses meilleurs amis Dohko et Suikyo, il a travaillé dur et a été promu Chevalier d''or de Bélier. Calme et posé, il fait passer la mission de Chevalier avant tout. Bien que jeune et immature, il possède la Télékinésie et est le seul des Douze Maisons à recevoir les pensées émises par le troublé Shijima.' WHERE id=55310;
UPDATE HeroStoryConfig SET describe='Il était autrefois Chevalier d''argent de Coupe et le professeur de Tenma. Devenu un assassin Suikyo de Garuda sous les ordres d''Hadès, Maître des Enfers, réapparaît au Sanctuaire. Il cache son véritable but et parie sa vie pour mener à bien sa mission, même s''il est considéré comme un traître.' WHERE id=65207;
UPDATE ItemConfig SET name='Suikyo', "desc"='Suikyo de Garuda, a abandonné le titre de Chevalier pour devenir le pionnier des Enfers, Il porte une lourde responsabilité que le commun des mortels ne peut pas connaître et il est déterminé à mourir au combat.' WHERE id=165207;
UPDATE ItemConfig SET name='Fragments de Suikyo de Garuda', "desc"='Fragments de Suikyo de Garuda : collectionnez les 60 pour synthétiser Suikyo de Garuda 5 étoiles.' WHERE id=265207;
UPDATE LoginGiftConfig SET icon='sds_zhu_3rdyuyue_icon' WHERE rowid=120;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=18;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=19;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=20;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=21;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=22;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=29;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=30;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=31;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=32;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=33;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=35;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=36;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=37;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=38;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=39;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=40;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=41;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=42;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=43;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=44;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=62;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=63;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=64;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=65;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=66;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=73;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=74;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=75;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=76;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=77;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=79;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=80;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=81;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=82;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=83;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=84;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=85;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=86;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=87;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=88;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=106;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=107;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=108;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=109;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=110;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=117;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=118;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=119;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=120;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=121;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=123;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=124;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=125;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=126;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=127;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=128;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=129;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=130;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=131;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=132;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=150;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=151;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=152;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=153;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=154;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=161;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=162;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=163;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=164;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=165;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=167;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=168;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=169;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=170;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=171;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=172;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=173;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=174;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=175;
UPDATE SevenAwardConfig SET checkpointNum=2 WHERE rowid=176;
UPDATE SkillTextConfig SET "desc"='Cristallise l''eau atmosphérique en crocs, formant de nombreuses lances de glace qui infligent des dégâts égaux à #6520721-101# de l''ATQ à l''ennemi dans la position opposée et rendent la cible en état <color=#ff902e>[Gel]</color> pour #6520721-203# secondes, tout en laissant les <color=#ff902e>[Crocs de glace]</color> dans le corps de la cible pendant 5 secondes, et en explosant à la fin, infligeant des dégâts réels égaux à #6520722-101# de l''ATQ de Suikyo aux ennemis.' WHERE id=652072101;
UPDATE SkillTextConfig SET "desc"='Suikyo stocke automatiquement <color=#2bff0e>1</color> cumul de <color=#ff902e>[Vapeur]</color> à chaque attaque normale et utilisation d''une technique de cycle, jusqu''à <color=#2bff0e>5</color> cumuls max. Chaque cumul de <color=#ff902e>[Vapeur]</color> augmente la vitesse de récupération de Cosmos de #65207321-101#.' WHERE id=652073101;
UPDATE SkillTextConfig SET "desc"='Suikyo est déterminé à mourir au combat et est incapable de bénéficier d''autres effets de soin que les siens : dans ce combat, les attaques seront toujours les <color=#ff902e>[coups critiques]</color>( ignorant l''effet de ne pas subir des coups critiques ), et plus ses PV sont élevés, moins il subit de dégâts, jusqu''à <color=#2bff0e>30 %</color> ; plus ses PV sont faibles, plus il inflige de dégâts, jusqu''à <color=#2bff0e>30 %</color>.' WHERE id=652074101;
